import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const c=vm.createContext({assert,console,structuredClone,document:{},localStorage:{}});
vm.runInContext(['runes.js','skills.js','engine.js','run.js'].map(f=>fs.readFileSync(new URL('../../public/2048/'+f,import.meta.url),'utf8')).join('\n')+`
let state;persist=()=>{};
function setup(egg='egg1',index=0){const s=fresh('math','mushroom',{...BASE,skillVersion:1,autoSkill:{egg,index},rune:egg,enemyHp:100000,damage:10,interval:100,critChance:0});s.board=Array(16).fill(null);s.board[0]={v:8,t:'a',f:0};s.board[1]={v:8,t:'d',f:0};s.board[4]={v:8,t:'x',f:0};s.board[5]={v:8,t:'x',f:0};s.hp=50;return s;}
function quiet(s){s.board=Array(16).fill(null);s.board[0]={v:2,t:'h',f:0};}
for(const egg of Object.keys(AUTO_SKILLS))for(let index=0;index<6;index++){
 const s=setup(egg,index);s.charge=5;assert.equal(autoCast(s,()=>.6),true,egg+index);assert.equal(s.charge,0);assert.equal(autoState(s).serial,1);assert.ok(Number.isFinite(s.hp)&&s.hp>=0&&s.hp<=s.cfg.hp);assert.ok(Number.isFinite(s.enemyHp)&&Number.isFinite(s.armor));assert.equal(skill(s),false);
 const copy=JSON.parse(JSON.stringify(s));assert.deepEqual(JSON.stringify(copy.auto),JSON.stringify(s.auto));quiet(copy);swipe(copy,'right',()=>.9);assert.ok(Number.isFinite(copy.hp));
}
const p=autoPower(setup());
const direct=setup('egg1',3);direct.cfg.skillBase={...direct.cfg};direct.cfg.attack*=100;direct.charge=5;autoCast(direct);assert.equal(100000-direct.enemyHp,Math.floor(.9*p.a),'direct ignores echo and crit');
for(let i=0;i<16;i++){const s=setup('egg6',0);s.board=Array(16).fill(null);s.charge=5;autoCast(s,()=>(i+.1)/16);assert.equal(s.auto.marks[0].cell,i,'random supports every empty socket');s.charge=5;autoCast(s,()=>.99);assert.equal(s.auto.marks[0].cell,i,'old mark retained');assert.equal(s.auto.marks.length,2);assert.notEqual(s.auto.marks[1].cell,i,'new mark is unique');}

for(const [egg,index]of [['egg6',0],['egg6',1],['egg6',4],['egg3',1],['egg3',3],['egg3',5]]){const s=setup(egg,index);s.board=Array(16).fill(null);for(let n=0;n<16;n++){s.charge=5;autoCast(s,()=>0);}assert.equal(s.auto.marks.length,16);assert.equal(new Set(s.auto.marks.map(m=>m.cell)).size,16);const full=JSON.stringify(s.auto.marks);s.charge=5;autoCast(s,()=>.9);assert.equal(JSON.stringify(s.auto.marks),full,'full board keeps existing marks');assert.equal(s.charge,0);const copy=JSON.parse(JSON.stringify(s));assert.deepEqual(copy.auto.marks,s.auto.marks,'all marks survive save');copy.enemyHp=0;finish(copy);assert.equal(copy.auto.marks.length,0,'room end clears all marks');}
const multi=setup('egg6',0);multi.auto={buffs:{},marks:[{cell:0,kind:'arrow'},{cell:4,kind:'guard'},{cell:15,kind:'double'}],serial:0};swipe(multi,'left',()=>.9);assert.equal(multi.auto.marks.length,1);assert.equal(multi.auto.marks[0].cell,15);assert.equal(multi.auto.markEvents.length,2);assert.equal(multi.armor,Math.floor(p.d*1.5)+Math.floor(p.d*1.1*1.15),'both marks activate on their own merge');
const legacy=setup('egg6',0);legacy.auto={buffs:{},mark:{cell:7,kind:'arrow'},serial:0};assert.equal(autoState(legacy).marks[0].cell,7);assert.equal(legacy.auto.mark,undefined);legacy.charge=5;autoCast(legacy,()=>0);assert.equal(legacy.auto.marks.length,2,'legacy saved mark is retained when adding');
const walk=setup('egg6',0);quiet(walk);walk.auto={buffs:{},marks:[{cell:3,kind:'arrow'}],serial:0};swipe(walk,'right',()=>.9);assert.equal(walk.auto.marks.length,1,'moving onto mark does not consume it');
const gardens=setup('egg3',3);gardens.auto={buffs:{},marks:[{cell:0,kind:'garden'},{cell:4,kind:'garden'}],serial:0};swipe(gardens,'left',()=>.9);assert.equal(gardens.auto.marks.length,0);assert.equal(gardens.board[0].v,32);assert.equal(gardens.board[4].v,32);assert.equal(100000-gardens.enemyHp,3*Math.floor(p.a*1.15),'all garden output precedes neighboring raises');

const noOp=setup('egg1',2);noOp.charge=5;autoCast(noOp);quiet(noOp);const snap=JSON.stringify(noOp);assert.equal(swipe(noOp,'left'),false);assert.equal(noOp.auto.buffs.burn.remaining,3);assert.equal(noOp.charge,0);
const burn=setup('egg1',2);burn.charge=5;autoCast(burn);assert.equal(burn.enemyHp,100000);for(let i=0;i<3;i++){quiet(burn);swipe(burn,'right',()=>.9);}assert.equal(100000-burn.enemyHp,3*Math.floor(p.a*.25));assert.equal(burn.auto.buffs.burn,undefined);
const early=setup('egg1',3);early.charge=4;early.countdown=1;swipe(early,'left',()=>.9);assert.equal(early.auto.serial,1);assert.ok(early.lastAttack,'Auto precedes attack');
const dead=setup('egg1',3);dead.charge=4;dead.enemyHp=1;swipe(dead,'left',()=>.9);assert.equal(dead.status,'won');assert.equal(dead.charge,5);assert.equal(dead.auto.serial,0,'do not cast at dead target');
const child=setup();child.cfg.autoSkill=null;child.charge=5;swipe(child,'left',()=>.9);assert.equal(child.auto.serial,0);assert.equal(skill(child),false);
const garden=setup('egg3',3);garden.board=Array(16).fill(null);garden.board[0]={v:32,t:'d',f:0};garden.board[1]={v:32,t:'a',f:0};garden.board[4]={v:8,t:'a',f:0};garden.board[5]={v:8,t:'a',f:0};garden.auto={buffs:{},mark:{cell:0,kind:'garden'},serial:0};swipe(garden,'left',()=>.9);assert.equal(garden.board[0].t,'x');assert.equal(garden.board[0].awake,true);assert.equal(garden.board[4].v,32);assert.equal(100000-garden.enemyHp,2*Math.floor(autoPower(garden,64).a*1.15)+Math.floor(autoPower(garden,16).a*1.15),'adjacent pair emits before doubling');
const number=setup('egg3',1);number.auto={buffs:{},mark:{cell:0,kind:'number'},serial:0};swipe(number,'left',()=>.9);assert.equal(number.board[0].v,32);
const bless=setup('egg3',5);bless.board=Array(16).fill(null);bless.board[0]={v:8,t:'d',f:0};bless.board[1]={v:8,t:'a',f:0};bless.auto={buffs:{},mark:{cell:0,kind:'blessing'},serial:0};swipe(bless,'left',()=>.9);assert.equal(100000-bless.enemyHp,3*Math.floor(p.a),'exactly 3, not 6 rounds');assert.equal(bless.board[0].awake,true);
const root=setup('egg3',4);root.board[0].f=2;root.charge=5;autoCast(root);assert.equal(root.board[0].f,2,'raise never clears roots');
const missing=setup('egg6',5);missing.board=Array(16).fill(null);missing.charge=5;autoCast(missing);assert.equal(missing.charge,0);assert.equal(missing.armor,Math.floor(p.d));
const low=setup('egg2',5);low.charge=4;low.countdown=1;swipe(low,'left',()=>.9);assert.equal(low.armor,Math.floor(p.d*.3),'new armor after reset');
const lethal=setup('egg1',5);lethal.hp=1;lethal.cfg.damage=1000;lethal.charge=4;lethal.countdown=1;swipe(lethal,'left',()=>.9);assert.equal(lethal.status,'lost');assert.equal(lethal.auto.buffs.counter,undefined);
const quake=setup('egg6',3);quake.charge=5;autoCast(quake);quake.board[0].t='x';quake.board[1].t='a';const out=runeMerge(quake,{v:16,t:'x'},1,1);assert.equal(out.d,Math.floor(p.d*1.1*1.5));assert.equal(runeState(quake).quake[0].power,out.d*.4,'no doubled armor bonus in counter');
run={skillVersion:1,room:2,companion:{stage:4,lane:'math',personality:'A',eggPrefix:'egg1',config:BASE},hero:'math',seed:1,relics:[],echo:false};state=setup();state.charge=5;const saved=state;hidePanel=()=>{};updateImages=()=>{};render=()=>{};enterBattle('mushroom');assert.equal(state.charge,5);assert.equal(state.auto,undefined);quiet(state);swipe(state,'right',()=>.9);assert.equal(state.auto.serial,1,'carry full charge casts after first valid swipe');
run={skillVersion:1,seed:1,relics:['echo','shadow','spark'],echo:true};state=setup('egg1',3);state.charge=3;runSwipe('left');assert.equal(state.auto.serial,1,'spark charges before Auto');assert.equal(state.cfg.attack,BASE.attack);assert.ok(state.board.some(t=>t?.v===16),'mirror once after Auto');
`,c);
console.log('PASS: all 36 casts, save/reload, random marks, no-op/expiry, Auto/attack ordering, death/Stage fallback, garden simultaneous merges, awakening/3 rounds, roots/missing targets, counter/rebuild, carry and relic synergy');
