const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../../public');
const out=path.resolve(__dirname,'../../output/relic-verification');fs.mkdirSync(out,{recursive:true});
const companion={petId:'fixture',id:'fixture',name:'คู่หูทดสอบ',stage:4,eggPrefix:'egg3',lane:'science',personality:'B',rarity:'legendary',stats:{hp:100,atk:20,def:20,spd:20,foc:20},image:'/pets/egg3_stage4_science_B.png',config:{hp:100,attack:5,armor:8,heal:8,bonus:.15,cooldown:5}};
const questions=[['1+1?',['2','3'],0],['2+2?',['4','5'],0],['3+3?',['6','7'],0]];
const server=http.createServer((req,res)=>{if(req.url.startsWith('/api/2048')){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(req.url.includes('/start')?{accountId:'fixture',companion,questions}:{accountId:'fixture',companions:[companion]}));return;}const file=path.join(root,decodeURIComponent(req.url.split('?')[0]),req.url.split('?')[0].endsWith('/')?'index.html':'');if(!file.startsWith(root)){res.writeHead(403).end();return;}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.ttf':'font/ttf'})[path.extname(file)]||'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/2048/';const browser=await chromium.launch({channel:'msedge',headless:true});const results=[];try{for(const width of [320,390,430]){const context=await browser.newContext({viewport:{width,height:width===320?568:844},isMobile:true,hasTouch:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>typeof forestAccount!=='undefined'&&forestAccount);await page.getByRole('button',{name:'เลือกคู่หู · เริ่มสำรวจ',exact:true}).click();await page.locator('[data-action=start]').click();await page.waitForFunction(()=>run?.phase==='battle'&&run.relicVersion===1);
 await page.evaluate(()=>{run.room=2;state.status='won';settleRun();});await page.getByRole('button').filter({hasText:'Common'}).count();await page.locator('#run-content .choice').first().click();assert.equal(await page.evaluate(()=>run.relics.length),1);
 await page.evaluate(()=>{run.coins=500;run.phase='doors';run.doors=['shop'];showPhase();});await page.locator('#run-content .choice').first().click();await page.locator('#run-content .choice').first().click();assert.equal(await page.evaluate(()=>run.relics.length),2);
 await page.reload();await page.waitForFunction(()=>run?.phase==='shop');await page.getByRole('button',{name:'เล่นต่อ',exact:true}).click();assert.equal(await page.evaluate(()=>run.relics.length),2);await page.getByRole('button',{name:'เดินทางต่อ',exact:true}).click();
 await page.evaluate(()=>{run.phase='doors';run.doors=['mushroom'];showPhase();});await page.locator('#run-content .choice').first().click();await page.locator('#relics button').first().click();await page.getByRole('button',{name:'กลับไปการเดินทาง',exact:true}).click();await page.evaluate(()=>{state.board=Array(16).fill(null);state.board[0]={v:2,t:'a',f:0};state.board[1]={v:2,t:'a',f:0};render();});const bounds=await page.locator('#board').boundingBox();const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:bounds.x+bounds.width*.8,y:bounds.y+bounds.height*.5}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:bounds.x+bounds.width*.2,y:bounds.y+bounds.height*.5}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(()=>state.moves===1);
 await page.evaluate(()=>{run.room=8;state.enemy='stag';state.status='won';settleRun();});assert.ok(await page.evaluate(()=>run.offers.some(id=>RELIC_V1.find(r=>r.id===id).grade==='Epic')));await page.locator('#run-content .choice').first().click();await page.locator('#run-content .choice').first().click();assert.equal(await page.evaluate(()=>run.room),9);
 await page.evaluate(()=>{for(const id of ['resonance','wind','oracle','interrupt'])if(!has(id))run.relics.push(id);state.cfg.relics=[...run.relics];render();});await page.screenshot({path:path.join(out,'mobile-'+width+'.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.reload();await page.waitForFunction(()=>run?.room===9);await page.getByRole('button',{name:'เล่นต่อ',exact:true}).click();assert.equal(errors.length,0,errors.join('\n'));for(const [enemy,asset] of [['slow_striker','crystal-heavy-v1.webp'],['glass_striker','crystal-swift-v1.webp']]){await page.evaluate(enemy=>enterBattle(enemy),enemy);await page.locator('.battle .enemy').evaluate(img=>img.decode());assert.ok((await page.locator('.battle .enemy').getAttribute('src')).endsWith(asset));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===320)await page.screenshot({path:path.join(out,enemy+'-320.png'),fullPage:true});await page.evaluate(enemy=>{run.phase='doors';run.doors=[enemy];showPhase();},enemy);await page.locator('#run-content .choice-art img').evaluate(img=>img.decode());assert.ok((await page.locator('#run-content .choice-art img').getAttribute('src')).endsWith(asset));}results.push({width,dedicatedEnemySprites:true,flow:'new run/reward/shop/purchase/reload/inspect/swipe/boss/level2/reload',errors});await context.close();}
 fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify({fixture:true,production:false,results},null,2));console.log(JSON.stringify(results));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
