import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const storage=new Map();
const c=vm.createContext({assert,console,structuredClone,document:{querySelector:()=>({textContent:'',replaceChildren(){}})},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)}});
const files=['runes.js','skills.js','engine.js','run.js','endless.js','relics.js','relic-engine.js','relic-run.js'];
vm.runInContext(files.map(f=>fs.readFileSync(new URL('../../public/2048/'+f,import.meta.url),'utf8')).join('\n')+`
let state,lastPanel;panel=(title,text,choices)=>{lastPanel={title,text,choices};};hidePanel=updateImages=render=runHUD=()=>{};
function setup(ids=[],skill={egg:'egg1',index:3},room=1){run={version:3,relicVersion:1,endlessVersion:1,balanceVersion:3,skillVersion:1,runeVersion:1,routeSeed:9,seed:123,room,coins:100,relics:ids,companion:{stage:4,eggPrefix:skill.egg,lane:'science',personality:'B',config:{...BASE}},questions:QUESTIONS,hero:'math',phase:'battle',history:[],started:Date.now()};state=undefined;enterBattle('mushroom');state.cfg.autoSkill=skill;state.cfg.enemyHp=state.enemyHp=100000;state.cfg.damage=10;state.cfg.interval=state.countdown=100;state.board=Array(16).fill(null);state.board[0]={v:2,t:'a',f:0};state.board[1]={v:2,t:'a',f:0};return state;}
assert.equal(RELIC_V1.length,40);for(const [grade,n]of [['Common',13],['Rare',17],['Epic',10]])assert.equal(RELIC_V1.filter(r=>r.grade===grade).length,n);assert.equal(RELIC_V1.filter(r=>r.cursed).length,7);assert.equal(new Set(RELIC_V1.map(r=>r.id)).size,40);
setup();run.companion.stage=2;assert.ok(relicOffers(40).every(id=>!RELIC_V1.find(r=>r.id===id).s4));run.companion.stage=4;assert.ok(!relicOffers(40).includes('pin'));run.relics=['seal','twins','unity'];const pool=relicOffers(40);assert.ok(pool.includes('pin'));assert.ok(!pool.includes('seed'));assert.ok(!pool.includes('blood'));assert.ok(relicOffers(3,true).some(id=>RELIC_V1.find(r=>r.id===id).grade==='Epic'));run.relics=RELIC_V1.map(r=>r.id);assert.equal(relicOffers().length,0);
setup(['corner','timing','drum']);state.countdown=1;assert.equal(relicFactor(state,{cell:0,same:true},'left','swipe',1),2.9);assert.equal(relicFactor(state,{cell:0},'left','pulse',1),1);
setup();const baseline=state.enemyHp;relicSwipe(state,'left',()=>.8);const ordinary=baseline-state.enemyHp;setup(['corner']);const before=state.enemyHp;relicSwipe(state,'left',()=>.8);assert.equal(before-state.enemyHp,Math.floor(ordinary*1.5));
for(const dir of DIRS){const b=Array(16).fill(null),indices=dir==='left'?[0,1,2,3]:dir==='right'?[3,2,1,0]:dir==='up'?[0,4,8,12]:[12,8,4,0];[2,2,4,8].forEach((v,i)=>b[indices[i]]={v,t:'a',f:0});const r=relicSlide(b,dir,'egg1',true);assert.equal(r.merges.length,2);assert.equal(r.board[indices[0]].v,8);assert.equal(r.board[indices[1]].v,8);}
setup(['pin','markCompass','seal']);state.board[3]={v:64,t:'a',f:0};autoMark(state,'arrow',()=>.9);assert.equal(state.auto.marks[0].cell,3);assert.equal(state.auto.marks[0].uses,2);const r={merged:[3],merges:[{v:128,t:'a'}]};autoPrepareMerges(state,r);assert.equal(state.auto.marks[0].uses,1);autoPrepareMerges(state,r);assert.equal(state.auto.marks.length,0);
setup(['resonance','growth','seal']);for(let i=0;i<3;i++){state.charge=5;autoCast(state,()=>.2);}assert.equal(state.auto.serial,4);assert.equal(relicState(state).autoCount,0);assert.equal(state.auto.marks.length,4);
setup(['battery','interrupt']);state.countdown=2;state.charge=5;assert.equal(autoCast(state,()=>.2),false);state.countdown=1;state.heavy=true;assert.equal(autoCast(state,()=>.2),true);assert.equal(state.heavy,false);assert.equal(relicState(state).interruptLocked,true);state.heavy=true;state.charge=5;autoCast(state,()=>.2);assert.equal(state.heavy,true);state.cfg.interval=1;state.countdown=1;state.armor=100;state.board[0]={v:2,t:'a'};state.board[1]={v:2,t:'a'};relicSwipe(state,'left',()=>.8);assert.equal(relicState(state).interruptLocked,false);
setup(['overflow']);state.hp=95;relicHeal(state,20,true);assert.equal(state.hp,100);assert.equal(state.armor,15);relicHeal(state,20);assert.equal(state.armor,35);
setup(['twins']);state.board=Array(16).fill(null);for(let i=0;i<100;i++){state.board.fill(null);spawn(state,()=>.01);assert.equal(state.board.find(Boolean).v,2);}
setup(['retention','thorn']);state.cfg.interval=state.countdown=1;state.armor=40;const eh=state.enemyHp;relicSwipe(state,'left',()=>.8);assert.equal(state.armor,15);assert.equal(eh-state.enemyHp,ordinary+10);
setup(['explosion']);state.board=Array.from({length:16},(_,i)=>({v:2**(1+i%4+(Math.floor(i/4)%2)*4),t:'a',f:0}));assert.equal(canMove(state.board),false);recover(state);assert.equal(state.hp,100);assert.equal(state.board.filter(Boolean).length,2);assert.equal(relicState(state).exploded,true);
setup(['explosion']);state.hp=0;state.status='lost';state.board=Array.from({length:16},(_,i)=>({v:2**(i%4+1+(Math.floor(i/4)%2)*4),t:'a'}));recover(state);assert.equal(state.hp,0);assert.equal(relicState(state).exploded,false);
setup(['pierce']);state.enemyHp=10;relicHit(state,40);assert.equal(run.relicCarry,30);state.status='won';run.room=2;enterBattle('beetle');assert.equal(run.relicCarry,0);assert.equal(state.enemyHp,state.cfg.enemyHp-15);
setup(['crown'],{egg:'egg1',index:3},8);run.crownStartLevel=1;state.status='won';state.enemy='stag';settleRun();assert.equal(run.crownWins,1);assert.equal(run.phase,'relic');assert.ok(run.offers.some(id=>RELIC_V1.find(r=>r.id===id).grade==='Epic'));run.room=9;enterBattle('mushroom');assert.equal(state.cfg.damage,Math.round(12*1.16));
setup(['jar','instant']);state.hp=70;run.room=2;enterBattle('beetle');assert.equal(state.hp,62);assert.equal(state.charge,state.cfg.cooldown);assert.equal(state.board.filter(t=>t?.v===16).length,3);
setup(['noRest']);run.phase='doors';run.doors=['rest'];state.hp=40;enterDoor('rest');assert.equal(run.phase,'relic');assert.equal(state.hp,40);
setup(['tome']);state.status='lost';settleRun();assert.equal(run.phase,'failed');
setup(['tome']);run.phase='quizReward';run.quizPassed=true;showPhase();lastPanel.choices[0].action();assert.equal(run.rewardRemaining,2);const first=run.offers[0];chooseRelic(first);assert.equal(run.rewardRemaining,1);chooseRelic(first);assert.equal(run.rewardRemaining,1);chooseRelic(run.offers[0]);assert.equal(run.phase,'doors');
setup(['heavyCoin']);run.phase='shop';run.offers=relicOffers();showPhase();assert.ok(lastPanel.choices.slice(0,-1).every(x=>x.disabled));const coins=run.coins;lastPanel.choices[0].action();assert.equal(run.coins,coins);
setup(['oracle','wind','resonance','interrupt','seal','pin']);state.charge=5;autoCast(state,rng);relicState(state).interruptLocked=true;run.relicCarry=31;run.offers=relicOffers();run.phase='shop';persist();const original=JSON.stringify(run);const next=relicState(state).nextRune;restoreRun(savedRun(saveKey()));assert.equal(JSON.stringify(run),original);assert.deepEqual(relicState(state).nextRune,next);
setup(['seal']);state.board=Array(16).fill(null);state.board[0]={v:2,t:'a'};const snapshot=JSON.stringify({board:state.board,rs:state.relic,charge:state.charge,moves:state.moves,seed:run.seed});assert.equal(relicSwipe(state,'left',rng),false);assert.equal(JSON.stringify({board:state.board,rs:state.relic,charge:state.charge,moves:state.moves,seed:run.seed}),snapshot);
// Both front and rear merged lineages can use one additional link.
for(const values of [[4,2,2],[2,2,2,2],[4,4,8,16]]){const b=Array(16).fill(null);values.forEach((v,i)=>b[i]={v,t:'a'});const r=relicSlide(b,'left','egg3',true);assert.equal(r.merges.length,values.every(v=>v===2)?3:2);assert.equal(r.board[0].v,values[0]===4&&values.length===4?16:8);}
setup(['gravity']);state.board[0]={v:2,t:'a',f:2};state.board[4]={v:2,t:'a'};const g=relicSlide(state.board,'down','egg1',false,false,state);assert.equal(g.board[0].f,2);assert.equal(g.hits.length,0);
setup(['chain','pin'],{egg:'egg3',index:1});state.board=Array(16).fill(null);state.board[0]={v:2,t:'x'};state.board[1]={v:2,t:'x'};state.board[2]={v:8,t:'x'};autoState(state).marks=[{cell:0,kind:'number',uses:2}];const marked=relicSlide(state.board,'left','egg3',true,true,state);assert.equal(marked.merges.length,2);assert.equal(marked.board[0].v,32);assert.equal(marked.board[0].awake,true);assert.equal(state.auto.marks.length,0);
for(const [egg,index]of [['egg3',1],['egg3',3],['egg3',5]]){setup(['resonance','seal','pin'],{egg,index});for(let i=0;i<3;i++){state.charge=5;autoCast(state,rng);}assert.equal(state.auto.serial,4);assert.ok(state.auto.marks.length<=16);assert.ok(state.auto.marks.every(m=>m.uses===2));for(let i=0;i<16;i++)state.board[i]={v:8,t:i%2?'a':'x'};const serial=state.auto.serial;relicSwipe(state,'left',rng);assert.ok(state.auto.serial<=serial+1);}
setup(['candle','battery']);state.countdown=1;state.charge=5;state.relicCombo=1.3;const hp=state.enemyHp;autoCast(state,()=>.8);assert.equal(hp-state.enemyHp,Math.floor(preRelicAutoPower(state).a*1.95*.9));
setup();run.relics=RELIC_V1.map(r=>r.id);relicReward(false,2);showPhase();lastPanel.choices[0].action();assert.equal(run.coins,150);assert.equal(run.phase,'doors');
setup();delete run.relicVersion;run.relics=['echo'];assert.equal(has('echo'),false);assert.equal(offers().length,0);run.endlessVersion=null;assert.equal(has('echo'),true);assert.equal(offers().length,3);
// An empty relic inventory preserves numerical combat outputs and all 36 Auto casts.
for(const egg of Object.keys(AUTO_SKILLS))for(let index=0;index<6;index++){setup([],{egg,index});state.started=1;state.hp=60;state.charge=5;const old=structuredClone(state);delete old.cfg.relicVersion;delete old.cfg.relics;delete old.relic;preRelicCast(old,()=>.7);autoCast(state,()=>.7);for(const key of ['hp','enemyHp','armor','charge'])assert.equal(state[key],old[key],egg+index+key);assert.equal(JSON.stringify(state.board),JSON.stringify(old.board));assert.deepEqual((state.auto?.marks||[]).map(m=>[m.cell,m.kind]),(old.auto?.marks||[]).map(m=>[m.cell,m.kind]));}
for(const egg of Object.keys(AUTO_SKILLS)){setup([],{egg,index:0});state.enemy='beetle';state.started=1;state.charge=0;state.board[0]={v:4,t:'x'};state.board[1]={v:4,t:'a'};runeState(state).burn=[{id:1,power:3,remaining:2}];const old=structuredClone(state);delete old.cfg.relicVersion;delete old.cfg.relics;delete old.relic;swipe(old,'left',()=>.8);relicSwipe(state,'left',()=>.8);for(const key of ['hp','enemyHp','armor','charge','countdown'])assert.equal(state[key],old[key],egg+key);}
setup(['oracle','wind','resonance','seal','pin'],{egg:'egg3',index:5});state.started=1;state.charge=5;runSwipe('left');const checkpoint=JSON.stringify(run);runSwipe('down');const continued=JSON.stringify({state,seed:run.seed});restoreRun(JSON.parse(checkpoint));runSwipe('down');assert.equal(JSON.stringify({state,seed:run.seed}),continued);
// Exercise every relic through actual bounded engine swipes, then JSON round-trip.
for(const r of RELIC_V1){setup([r.id]);let i=0;while(state.status==='playing'&&i<120){relicSwipe(state,DIRS[i++%4],rng);}assert.ok(Number.isFinite(state.hp)&&Number.isFinite(state.enemyHp)&&Number.isFinite(state.armor));assert.doesNotThrow(()=>JSON.parse(JSON.stringify(state)));}
`,c);
console.log('PASS relic catalog, filters, additive output, chain directions, marks, repeats, interruption lock, overflow, twins, armor/thorns, explosion/death, carry, crown, jar, tome, wells, shop, save/reload, no-op and all 40 engine smoke cases');
